
// tests/api/sample-api.spec.js
const { test, expect } = require('@playwright/test');
const { json } = require('node:stream/consumers');

test.describe('Sample API Tests', () => {

  test('GET API - Fetch user details', async ({ request, baseURL }) => {
    const response = await request.get(baseURL+'/products/2');

    expect(response.status()).toBe(200);
    expect(response.ok()).toBeTruthy();
    const text = await response.text();
    const body = JSON.parse(text); // only if the API returns valid JSON
    expect(body.data).toHaveProperty('id', 2);
    //expect(body.data.email).toContain('@reqres.in');
  });

  test('POST API - Create user', async ({ request }) => {
    const payload = {
      name: "Ramya",
      job: "Engineer"
    };

    const response = await request.post('https://reqres.in/api/users', {
      data: payload,
    });

    expect(response.status()).toBe(201);

    const body = await response.json();

    expect(body).toHaveProperty('name', payload.name);
    expect(body).toHaveProperty('job', payload.job);
    expect(body).toHaveProperty('id');       // autogenerated
    expect(body).toHaveProperty('createdAt'); // autogenerated
  });


  test('GET API with Bearer Token', async ({ request }) => {
    const response = await request.get('https://api.example.com/profile', {
      headers: {
        Authorization: `Bearer your_token_here`
      }
    });
    expect(response.headers()).toBe("application/json");
    expect(response.status()).toBe(200);

    const data = await response.json();
    console.log(data);
  });


});
